### ISSUE TITLE
Question on the number of channels

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [VolksEEG/VolksEEG#13]
Hi,

I have been following your github for some time now and am really eager to see what comes out of it :)

My question is : given that you first plan on creating an 8 channel version, how hard do you expect it would be to extend the project to support 16 or more channels? Is it simply a matter of duplicating the electronics or is it vastly more complex?

Context: I am a med student and python dev with very basic understanding of electronics so I wanted your take on this.

Thanks!

**Comment by alcohen** [comment]
In _theory_ it's not  big deal - mostly just scaling the electronics. The ADS1299 chip at the heart of VolksEEG has a daisy-chain mode to add devices and everything syncs up/behaves.

**Comment by thiswillbeyourgithub** [comment]
Thank you very much :).
