### ISSUE TITLE
Question on expected price of unit

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [VolksEEG/VolksEEG#14]
Hi, it's me again :)

I was planning on buying a headset from openBCI in a few months but I heard about your project.

Being not that rich and with a very specific use case in mind, I am wondering if it would not be better to wait for *your* device to be fully prototyped if it was *substancially* cheaper than openBCI's headset.

So my question is: could you give me a range of expected unit price to your 8 channel version? Either to buy from you or to source myself (I'm talking mostly electronics and electrodes, I can deal with making the headset or DIYing missing stuff, but I can't write the firmware :/).

Looking at OpenBCI's shop I'm seeing a bare minimum of $850:
* Cython board (8 channel): $749
* cables and dry electrodes: $90

I understand that you're project is not directly aimed at consumers and is very early but I really have no idea if your aiming at the same kind of price or 5 times less or 5 times more :)

Thanks!

**Comment by alcohen** [comment]
Our primary "use case" for sales is for studies by researchers at institutions that have an IRB (Institutional Review Board).

We haven't yet internally discussed and made a decision about whether or how to sell units for use outside of that scenario. 

However, since this is open source, you could build it yourself. The parts cost, less PCBs, will likely be in the $300-$400 range (without electrodes) plus a Windows PC. PCBs should be under $100.

I hope that's helpful!

**Comment by thiswillbeyourgithub** [comment]
Thank you very much, this is very helpful.

I see you mentionning windows in the repo but I am on linux. Although your main app will be on windows, do you intend to make at least a minimal API that would be cross platform? Similar to OpenBCI's python API.

I don't really need a GUI, I'm mostly after an API to access data in realtime for machine learning.

Implementing a linux API myself is beyond my skills but if you supplied one I would gladly create the first community GUI / software suite :)

But in the end, OpenBCI already has a cross platform software, have you considered forking their app or making your prototype compatible with their software? Wouldn't that speed up your project?

Thanks :)

**Comment by rtullybarr** [comment]
Hey!

I'm working on the desktop software side - we're currently using WPF for the GUI, which is not itself cross-platform, but we're using .NET core for all the actual data capture and processing. This should open up the ability to have a cross-platform API.

I'll definitely look at OpenBCI, as I wasn't aware of its existence before now! It sounds beneficial to at least look into making our work compatible with it.

**Comment by thiswillbeyourgithub** [comment]
Hi!

Glad to hear I was useful in making you discover their stuff :). I am surprised that you had not heard of it as they are the top results when you search for "open source EEG" and are *approved* (or something like that) by the FDA. Doesn't that make them a direct competitor? Does that change anything to your endeavor? If not why not? :)

Regarding your last question:
I'm going to admit right away that I'm a beginner regarding EEG. But I'm a med student with a clear interest toward it, a python developper and very interested in AI.

* Hence what I would be after is at least being able to access raw data in an accessible format. For example, in [this video at 9min30s](https://www.youtube.com/watch?v=Dgo7F-lpyYE) youtuber "sentdex" use a simple python import statement and gets an output. He then creates a little script to make sure the data dumps comes with a consistent timing. If I have this I can probably manage to get what I need to do machine learning stuff, plot things etc. I will of course make everything open source and contribute to the community :)
* BUT if you want to and can go the extra mile, making your device compatible with their software suite (same API, same GUI, same everything) will not hurt.

In the end, I don't want to interfere with the scope of the project. I can manage with the bare minimum (API with raw data), and would definitely appreciate it if your project could resuse already existing projects.

(btw: they are compatible with LSL too #16)

**Comment by alcohen** [comment]
Hi there!

The primary difference is that Volks EEG has the goal of becoming a full-fledged FDA-cleared device. Our first generation device will be similar to theirs as it will be appropriate for research, although it will prove out some new things.

Second iteration will be developed as a medical device, meeting FDA/EU regs.

That said, using the open BCI software front end as a milestone might make good sense, we should review the interface and see what the effort entails. 

In principle, it would also be good for our own front end to support multiple output formats, which should be do-able over time.

Thanks for your input and questions, they are very helpful!

**Comment by thiswillbeyourgithub** [comment]
Thank you for your answer.

I can't wait to see what comes out of your project :)
